services:
  server:
    build: 
      context: ./server/
      target: production
    environment:
      DB_HOST: db
      DB_USER: root
      DB_NAME: classweb
      DB_PASSWORD_FILE: /run/secrets/db-password-file
    secrets:
      - db-password-file
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password-file
      MYSQL_DATABASE: classweb
    secrets:
      - db-password-file
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping"]
      interval: 3s
      timeout: 4s
      retries: 5
secrets:
  db-password-file: 
    file: secrets/root-password.txt