services:
  server: 
    build:
      context: server
      target: development
    ports:
      - 3000:3000
      - 4000:4000
    environment:
      DB_HOST: db
      DB_USER: root
      DB_NAME: classweb
      DB_PASSWORD_FILE: /run/secrets/db-password-file
    secrets:
      - db-password-file
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password-file
      MYSQL_DATABASE: classweb
    secrets:
      - db-password-file
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 3s
      timeout: 4s
      retries: 10
    ports:
      - 3306:3306
  client:
    build:
      context: client
      target: development
    ports:
      - 5000:3000
    depends_on:
      - server
secrets:
  db-password-file:
    file: secrets/root-password.txt
